import {
  mcpGetPayment,
  mcpListPayments,
  mcpGetOrder,
  mcpGetRefunds,
  mcpGetSettlements,
  mcpGetDisputes,
  mcpCreatePaymentLink,
  mcpCreateOrder,
} from "./mcpClient"

export type AttachedDocument = {
  name: string
  type?: string
  size?: string
  content?: string
}

export type ChatMessage = {
  text: string
  isUser: boolean
}

// User-provided API key from .env / prompt
const PRIMARY_GEMINI_KEY =
  import.meta.env.VITE_GEMINI_API_KEY || "AIzaSyCnZP7ty2Y0e77HcM7KW7j0o6R8Qukdv1I"
const FALLBACK_GEMINI_KEY = "AIzaSyAtkF3Otrj9rmmcYaAlp3YUd_qf923da9Q"
const MODEL_NAME = "gemini-2.5-flash"
const BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

const RAZORPAY_TOOL_DECLARATIONS = [
  {
    name: "get_payment_details",
    description:
      "Fetch detailed information for a specific Razorpay payment ID (e.g. pay_...). Returns status, amount, method, customer details, and error reasons if failed.",
    parameters: {
      type: "object",
      properties: {
        payment_id: {
          type: "string",
          description: "The payment ID, starting with pay_",
        },
      },
      required: ["payment_id"],
    },
  },
  {
    name: "search_payments",
    description:
      "Search or list payments by status (all, captured, failed, refunded, authorized), customer name/email, or free text query.",
    parameters: {
      type: "object",
      properties: {
        status: {
          type: "string",
          description: "Filter by status: 'captured', 'failed', 'refunded', 'authorized', or 'all'",
        },
        query: {
          type: "string",
          description: "Search keyword in customer name, email, description, or order ID",
        },
        limit: {
          type: "number",
          description: "Maximum number of records to return (default 5)",
        },
      },
    },
  },
  {
    name: "get_order_details",
    description: "Look up order information by Razorpay order ID (e.g. order_...).",
    parameters: {
      type: "object",
      properties: {
        order_id: {
          type: "string",
          description: "The order ID, starting with order_",
        },
      },
      required: ["order_id"],
    },
  },
  {
    name: "create_order",
    description:
      "Create a new live unpaid order on Razorpay for a specified amount in INR, receipt identifier, and description.",
    parameters: {
      type: "object",
      properties: {
        amount: {
          type: "number",
          description: "Order amount in Indian Rupees (₹), e.g. 1499",
        },
        receipt: {
          type: "string",
          description: "Receipt or invoice reference ID (e.g. rcpt_101)",
        },
        description: {
          type: "string",
          description: "Product description or plan name for the order",
        },
      },
      required: ["amount"],
    },
  },
  {
    name: "get_refund_status",
    description: "Retrieve refund status for a specific refund ID (rfnd_...) or payment ID (pay_...).",
    parameters: {
      type: "object",
      properties: {
        payment_id: {
          type: "string",
          description: "The payment ID to find refunds for",
        },
      },
    },
  },
  {
    name: "get_settlements_info",
    description: "List recent payout settlements deposited into the merchant's bank account.",
    parameters: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "get_disputes_info",
    description: "List customer disputes or chargebacks needing merchant evidence.",
    parameters: {
      type: "object",
      properties: {},
    },
  },
  {
    name: "create_payment_link",
    description:
      "Generate a live Razorpay payment link and scannable UPI QR code to pay for an unpaid order or specified amount.",
    parameters: {
      type: "object",
      properties: {
        order_id: {
          type: "string",
          description: "The order ID to pay for, e.g. order_TXGPnb2izSqLLF",
        },
        amount: {
          type: "number",
          description: "Amount in Indian Rupees (₹), e.g. 1499. Optional if order_id is provided.",
        },
        description: {
          type: "string",
          description: "Reason or description of the payment",
        },
      },
    },
  },
]

/**
 * Executes a function call generated by Gemini directly via Razorpay MCP tools.
 */
async function executeRazorpayTool(name: string, args: any): Promise<any> {
  switch (name) {
    case "get_payment_details":
      return await mcpGetPayment(args.payment_id || "")

    case "search_payments":
      return await mcpListPayments({
        status: args.status,
        query: args.query,
        limit: args.limit || 6,
      })

    case "get_order_details":
      return await mcpGetOrder(args.order_id || "")

    case "create_order":
      return await mcpCreateOrder({
        amount: args.amount,
        receipt: args.receipt,
        notes: args.description ? { description: args.description } : undefined,
      })

    case "create_payment_link":
      return await mcpCreatePaymentLink({
        order_id: args.order_id,
        amount: args.amount,
        description: args.description,
      })

    case "get_refund_status":
      return await mcpGetRefunds(args.payment_id)

    case "get_settlements_info":
      return await mcpGetSettlements()

    case "get_disputes_info":
      return await mcpGetDisputes()

    default:
      return { error: `MCP Tool '${name}' not recognized.` }
  }
}

async function postToGemini(body: any, apiKey: string) {
  const url = `${BASE_URL}/models/${MODEL_NAME}:generateContent?key=${apiKey}`
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  })
  return res
}

/**
 * Calls Google Gemini API with fallback resilience across configured API keys.
 */
async function callGeminiWithFallback(body: any): Promise<any> {
  let activeKey = PRIMARY_GEMINI_KEY
  let res = await postToGemini(body, activeKey)

  if (!res.ok) {
    const errText = await res.text()
    // If the user-provided key is invalid or unauthorized, fail over to fallback key
    if (res.status === 400 || res.status === 403 || errText.includes("API_KEY_INVALID")) {
      console.warn(
        `Primary Gemini API key rejected (${res.status}). Switching to backup key...`
      )
      activeKey = FALLBACK_GEMINI_KEY
      res = await postToGemini(body, activeKey)
      if (!res.ok) {
        const errText2 = await res.text()
        throw new Error(`Gemini API Error: ${errText2}`)
      }
    } else {
      throw new Error(`Gemini API Error (${res.status}): ${errText}`)
    }
  }

  return { data: await res.json(), activeKey }
}

// Track Gemini quota status to enable instantaneous fallback
export let isGeminiQuotaExhausted = false

export function resetGeminiQuotaStatus() {
  isGeminiQuotaExhausted = false
}

export function getGeminiQuotaStatus(): boolean {
  return isGeminiQuotaExhausted
}

/**
 * Executes Google Gemini 2.5 Flash with full Model Context Protocol tools.
 */
export async function getGeminiSupportResponse(
  query: string,
  history: ChatMessage[],
  attachedDocs: AttachedDocument[] = []
): Promise<string> {
  return await _legacyGeminiCall(query, history, attachedDocs)
}

/**
 * Legacy Gemini function kept for future reactivation:
 */
export async function _legacyGeminiCall(
  query: string,
  history: ChatMessage[],
  attachedDocs: AttachedDocument[] = []
): Promise<string> {
  // Format message history
  const contents: any[] = history.map((msg) => ({
    role: msg.isUser ? "user" : "model",
    parts: [{ text: msg.text }],
  }))

  // Add current user query
  contents.push({
    role: "user",
    parts: [{ text: query }],
  })

  let docContextPrompt = ""
  if (attachedDocs.length > 0) {
    docContextPrompt = "\n\n### User-Attached Evidence Documents:\n"
    for (const doc of attachedDocs) {
      docContextPrompt += `\n--- Document: "${doc.name}" (${doc.size || "Unknown size"}) ---\n`
      if (doc.content) {
        const preview =
          doc.content.length > 8000
            ? doc.content.slice(0, 8000) + "\n...[truncated]"
            : doc.content
        docContextPrompt += `${preview}\n`
      } else {
        docContextPrompt += `(File attached by user: ${doc.name})\n`
      }
    }
    docContextPrompt +=
      "\nYou can use the details from these attached documents to analyze logs, receipts, order numbers, error codes, and customer inquiries.\n"
  }

  const systemInstruction = {
    parts: [
      {
        text: `You are an intelligent, expert Razorpay Support & Merchant Virtual Agent powered directly by the Razorpay Model Context Protocol (MCP).
You have access to live MCP tools:
- 'get_payment_details': Fetch full payment details (e.g. pay_...).
- 'search_payments': Find transactions by status (captured, failed, refunded), customer email, or keyword.
- 'get_order_details': View order totals, paid amounts, and receipt IDs.
- 'get_refund_status': Check refund records.
- 'get_settlements_info': View bank settlement payouts and UTR numbers.
- 'get_disputes_info': Check chargebacks and evidence deadlines.

Always execute these tools when asked about transactions, payments, orders, refunds, settlements, or disputes.
State exact amounts in Indian Rupees (₹), transaction IDs, payment methods, customer names, and clear explanations.
Keep responses concise, polite, professional, and directly helpful (typically 2-4 sentences).
Multilingual support: Automatically match the user's language (English, Hindi, etc.).${docContextPrompt}`,
      },
    ],
  }

  const tools = [{ functionDeclarations: RAZORPAY_TOOL_DECLARATIONS }]

  try {
    // 1. First Call to Gemini
    const { data: data1, activeKey } = await callGeminiWithFallback({
      contents,
      systemInstruction,
      tools,
    })

    const candidate1 = data1.candidates?.[0]
    const part1 = candidate1?.content?.parts?.[0]

    // Check if Gemini invoked an MCP tool
    if (part1 && part1.functionCall) {
      const { name, args } = part1.functionCall
      const toolOutput = await executeRazorpayTool(name, args)

      // Add model's functionCall to conversation
      contents.push(candidate1.content)

      // Add functionResponse to conversation
      contents.push({
        role: "tool",
        parts: [
          {
            functionResponse: {
              name,
              response: toolOutput,
            },
          },
        ],
      })

      // 2. Second Call to Gemini to synthesize natural answer
      const res2 = await postToGemini(
        {
          contents,
          systemInstruction,
          tools,
        },
        activeKey
      )

      if (!res2.ok) {
        const errText2 = await res2.text()
        throw new Error(`Gemini API step 2 returned status ${res2.status}: ${errText2}`)
      }

      const data2 = await res2.json()
      const text2 = data2.candidates?.[0]?.content?.parts?.[0]?.text
      if (text2) return text2.trim()
    }

    // Direct text response without tool call
    if (part1 && part1.text) {
      return part1.text.trim()
    }

    throw new Error("No valid response candidate returned by Gemini.")
  } catch (err: any) {
    if (
      err.message &&
      (err.message.includes("429") ||
        err.message.includes("RESOURCE_EXHAUSTED") ||
        err.message.includes("quota"))
    ) {
      isGeminiQuotaExhausted = true
    }
    console.error("[AI] Gemini execution error:", err.message)
    throw new Error(`Gemini API Error: ${err.message}`)
  }
}

